#!/usr/bin/env bash
set -euo pipefail

# ─────────────────────────────────────────────
#  smallmd setup.sh
#  Tested on: Ubuntu 22.04/24.04, Debian 12
#  Usage: sudo bash setup.sh --name mysite [--domain example.com] [--deploy-user USER]
#  Multiple sites: run again with a different --name and --domain
# ─────────────────────────────────────────────

PHP_VER=""
SITE_NAME=""
DEPLOY_USER=""
DOMAIN=""

# ── Parse args ───────────────────────────────
while [[ $# -gt 0 ]]; do
    case $1 in
        --name)
            SITE_NAME="$2"
            shift 2
            ;;
        --deploy-user)
            DEPLOY_USER="$2"
            shift 2
            ;;
        --domain)
            DOMAIN="$2"
            shift 2
            ;;
        --list)
            echo "Installed smallmd sites:"
            for conf in /etc/nginx/sites-available/smallmd-*; do
                [[ -f "$conf" ]] || continue
                name="${conf##*smallmd-}"
                domain=$(grep -oP '(?<=server_name ).*?(?=;)' "$conf" || echo "(no domain)")
                dir="/var/www/$name"
                echo "  $name  →  $domain  ($dir)"
            done
            exit 0
            ;;
        *)
            echo "  ✗ Unknown argument: $1"
            exit 1
            ;;
    esac
done

print_step() { echo -e "\n\033[1;34m──\033[0m $1"; }
print_ok()   { echo -e "  \033[0;32m✓\033[0m $1"; }
print_err()  { echo -e "  \033[0;31m✗\033[0m $1"; exit 1; }

# ── Validate --name ──────────────────────────
if [[ -z "$SITE_NAME" ]]; then
    print_err "--name is required (e.g. sudo bash setup.sh --name mysite --domain example.com)"
fi

# Restrict to safe characters for use in paths, pool names, etc.
if [[ ! "$SITE_NAME" =~ ^[a-z0-9_-]+$ ]]; then
    print_err "--name may only contain lowercase letters, numbers, hyphens and underscores"
fi

# Derived paths — everything namespaced under SITE_NAME
INSTALL_DIR="/var/www/${SITE_NAME}"
NGINX_CONF="/etc/nginx/sites-available/smallmd-${SITE_NAME}"
FPM_POOL_NAME="smallmd_${SITE_NAME}"
SUDOERS_FILE="/etc/sudoers.d/smallmd-${SITE_NAME}"

# ── 0. Must be root ──────────────────────────
if [[ $EUID -ne 0 ]]; then
    print_err "Please run as root: sudo bash setup.sh --name ${SITE_NAME}"
fi

# ── 0b. Collision check ──────────────────────
# Allow running from inside the install dir (e.g. re-installing in place)
SCRIPT_DIR="$(realpath "$(dirname "${BASH_SOURCE[0]}")")"
if [[ -d "$INSTALL_DIR" && "$SCRIPT_DIR" != "$INSTALL_DIR" ]]; then
    print_err "$INSTALL_DIR already exists — choose a different --name or remove it first"
fi

# ── 0c. Create deploy user if requested ──────
if [[ -n "$DEPLOY_USER" ]]; then
    print_step "Setting up deploy user: $DEPLOY_USER"
    if id "$DEPLOY_USER" &>/dev/null; then
        print_ok "User $DEPLOY_USER already exists"
    else
        useradd -m -s /bin/bash "$DEPLOY_USER"
        print_ok "Created user: $DEPLOY_USER"
    fi

    usermod -aG www-data "$DEPLOY_USER"
    print_ok "Added $DEPLOY_USER to www-data group"

    # Scoped sudoers — only what's needed for deploys
    cat > "$SUDOERS_FILE" <<SUDOERS
# Generated by smallmd setup.sh for site: ${SITE_NAME}
${DEPLOY_USER} ALL=(ALL) NOPASSWD: /bin/systemctl reload nginx, /bin/systemctl restart php*-fpm
SUDOERS
    chmod 440 "$SUDOERS_FILE"
    print_ok "Sudoers written to $SUDOERS_FILE"
fi

# ── 1. Detect distro ─────────────────────────
print_step "Detecting system"
if [[ -f /etc/os-release ]]; then
    . /etc/os-release
    OS=$ID
    print_ok "Detected: $PRETTY_NAME"
else
    print_err "Cannot detect OS"
fi

# ── 2. Install deps ──────────────────────────
print_step "Installing nginx, PHP, composer"

apt-get update -qq

# Pick the right PHP version
if apt-cache show php8.3 &>/dev/null; then
    PHP_VER="8.3"
elif apt-cache show php8.2 &>/dev/null; then
    PHP_VER="8.2"
else
    if [[ $OS == "ubuntu" ]]; then
        apt-get install -y -qq software-properties-common
        add-apt-repository -y ppa:ondrej/php
        apt-get update -qq
        PHP_VER="8.3"
    else
        apt-get install -y -qq apt-transport-https lsb-release ca-certificates curl
        curl -sSo /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg
        echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" \
            > /etc/apt/sources.list.d/php.list
        apt-get update -qq
        PHP_VER="8.3"
    fi
fi

apt-get install -y -qq \
    nginx \
    php${PHP_VER}-fpm \
    php${PHP_VER}-cli \
    php${PHP_VER}-mbstring \
    php${PHP_VER}-xml \
    php${PHP_VER}-zip \
    unzip \
    curl

print_ok "nginx + PHP ${PHP_VER} installed"

if [[ -n "$DOMAIN" ]]; then
    apt-get install -y -qq certbot python3-certbot-nginx
    print_ok "certbot installed"
fi

if ! command -v composer &>/dev/null; then
    curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    print_ok "composer installed"
else
    print_ok "composer already present"
fi

# ── 3. Copy files ────────────────────────────
print_step "Installing smallmd to $INSTALL_DIR"

if [[ ! -f "$SCRIPT_DIR/composer.json" ]]; then
    print_err "Run setup.sh from the smallmd repo directory (composer.json not found in $SCRIPT_DIR)"
fi

mkdir -p "$INSTALL_DIR"
rsync -a --exclude='.git' --exclude='vendor' "$SCRIPT_DIR/" "$INSTALL_DIR/"
print_ok "Files copied"

# ── 3b. Write base_url into site.yaml if domain given ──
if [[ -n "$DOMAIN" ]]; then
    YAML="$INSTALL_DIR/config/site.yaml"
    if grep -q '^base_url:' "$YAML"; then
        sed -i "s|^base_url:.*|base_url: https://${DOMAIN}|" "$YAML"
    else
        echo "base_url: https://${DOMAIN}" >> "$YAML"
    fi
    print_ok "base_url set to https://${DOMAIN} in site.yaml"
fi

# ── 4. Composer install ──────────────────────
print_step "Installing PHP dependencies"
cd "$INSTALL_DIR"
composer install --no-dev --optimize-autoloader --quiet
print_ok "Dependencies installed"

# ── 5. Permissions ───────────────────────────
print_step "Setting permissions"
mkdir -p "$INSTALL_DIR/var"
if [[ -n "$DEPLOY_USER" ]]; then
    chown -R "$DEPLOY_USER":www-data "$INSTALL_DIR"
else
    chown -R www-data:www-data "$INSTALL_DIR"
fi
chmod -R 755 "$INSTALL_DIR"
chmod -R 775 "$INSTALL_DIR/var"
print_ok "Permissions set"

# ── 6. PHP-FPM pool ──────────────────────────
print_step "Configuring PHP-FPM pool: ${FPM_POOL_NAME}"

FPM_POOL_FILE="/etc/php/${PHP_VER}/fpm/pool.d/${FPM_POOL_NAME}.conf"
FPM_SOCK="/run/php/${FPM_POOL_NAME}.sock"
POOL_USER="${DEPLOY_USER:-www-data}"

cat > "$FPM_POOL_FILE" <<FPM
[${FPM_POOL_NAME}]
user  = ${POOL_USER}
group = www-data

listen = ${FPM_SOCK}
listen.owner = www-data
listen.group = www-data
listen.mode  = 0660

pm                   = dynamic
pm.max_children      = 5
pm.start_servers     = 1
pm.min_spare_servers = 1
pm.max_spare_servers = 3

; Restrict this pool to its own install dir
php_admin_value[open_basedir] = ${INSTALL_DIR}:/tmp
php_admin_value[error_log]    = ${INSTALL_DIR}/var/php-error.log
FPM

print_ok "FPM pool written to $FPM_POOL_FILE"

# ── 7. nginx config ──────────────────────────
print_step "Configuring nginx"

SERVER_NAME="${DOMAIN:-_}"

# Only use default_server if no other site has claimed it
if grep -rl 'default_server' /etc/nginx/sites-enabled/ &>/dev/null; then
    LISTEN_OPTS="listen 80;"$'\n'"    listen [::]:80;"
else
    LISTEN_OPTS="listen 80 default_server;"$'\n'"    listen [::]:80 default_server;"
fi

cat > "$NGINX_CONF" <<NGINX
server {
    ${LISTEN_OPTS}
    server_name ${SERVER_NAME};

    root ${INSTALL_DIR}/public;
    index index.php;

    # /assets/ handled by PHP — theme switchable via site.yaml, no nginx change needed
    location / {
        try_files \$uri \$uri/ /index.php?\$query_string;
    }

    location ~ \.php$ {
        include        fastcgi_params;
        fastcgi_pass   unix:${FPM_SOCK};
        fastcgi_param  SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
        fastcgi_param  DOCUMENT_ROOT   \$document_root;
    }

    location ~ \.(md|yaml|json)$ { deny all; }
    location ~ /\. { deny all; }
}
NGINX

ln -sf "$NGINX_CONF" "/etc/nginx/sites-enabled/smallmd-${SITE_NAME}"

# Disable nginx default site if it exists and no other sites are present
SITE_COUNT=$(ls /etc/nginx/sites-enabled/smallmd-* 2>/dev/null | wc -l)
if [[ -f /etc/nginx/sites-enabled/default && "$SITE_COUNT" -eq 1 ]]; then
    rm /etc/nginx/sites-enabled/default
    print_ok "Disabled nginx default site"
fi

nginx -t -q && print_ok "nginx config valid"

# ── 8. Start / restart services ──────────────
print_step "Starting services"
systemctl enable --now php${PHP_VER}-fpm nginx
systemctl restart php${PHP_VER}-fpm nginx
print_ok "nginx and PHP-FPM running"

# ── 9. TLS via certbot ───────────────────────
if [[ -n "$DOMAIN" ]]; then
    print_step "Obtaining TLS certificate for $DOMAIN"
    certbot --nginx -d "$DOMAIN" --non-interactive --agree-tos --register-unsafely-without-email \
        && print_ok "TLS certificate installed — HTTPS active" \
        || print_err "certbot failed — is DNS pointing at this server yet?"
fi

# ── 10. Done ─────────────────────────────────
echo ""
echo -e "\033[1;32m✓ ${SITE_NAME} is live!\033[0m"
echo ""
echo "  Site name      : ${SITE_NAME}"
echo "  Content folder : $INSTALL_DIR/content/"
echo "  Config         : $INSTALL_DIR/config/site.yaml"
echo "  Theme          : $INSTALL_DIR/themes/default/"
echo "  FPM pool       : $FPM_POOL_FILE"
echo "  nginx config   : $NGINX_CONF"
echo ""
echo "  To add a page  : create a .md file in $INSTALL_DIR/content/"
echo "  To edit config : nano $INSTALL_DIR/config/site.yaml"
echo "  To list sites  : sudo bash setup.sh --list"
echo ""
if [[ -n "$DOMAIN" ]]; then
    echo "  Visit https://$DOMAIN"
else
    echo "  Visit http://$(hostname -I | awk '{print $1}')"
fi
echo ""
if [[ -n "$DEPLOY_USER" ]]; then
    echo "  Deploy user    : $DEPLOY_USER"
    echo "  Sudoers        : $SUDOERS_FILE"
    echo ""
fi
